language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - memcached

env:
  - DB=mysql
  - DB=pqsql

before_install:
  - sh tests/ci/$DB.sh;

install:
  - composer --prefer-source install

script:
  - phpunit -v --configuration tests/travis/$DB.travis.xml
