language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - memcached

env:
  - DB=mysql
  - DB=pqsql

before_install:
  - sh tests/ci/$DB.sh;

install:
  - composer --prefer-source install

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/ tests/
  - phpunit -v --debug --coverage-clover=coverage.clover --configuration tests/travis/$DB.travis.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
